name: Deploy to AWS CloudFormation

on:
  #push:
  #  branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Infra to cloudformation/AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Deploy with CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: EC2Stack
          template: Untitled-1.yml
          #no-fail-on-empty-changeset: "1"
